spring:
  application:
    name: arrival-app
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
server:
  shutdown: graceful

app:
  client-protocol: http
  plane-client:
    url: localhost
    port: 9000
  gate-client:
    url: localhost
    port: 9001
  airliner-client:
    url: localhost
    port: 9002
